### ISSUE TITLE
client error: Unexpected Response: 503 (Service Unavailable)

### ISSUE THREAD

**Issue by yawudede** [GanymedeNil/document.ai#10]
import_data.py error
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 503 (Service Unavailable)
Raw response content:
b''
how to set the parameters of the clients?

**Comment by GanymedeNil** [comment]
Have you set up a proxy? If so, you need to set "no_proxy" to skip the service address of Qdrant.

**Comment by hillerliao** [comment]
老师们能指点一下吗？我也碰到这个问题了，不知道怎么设置 no_proxy

**Comment by kiuyaku** [comment]
> 您是否设置了代理？如果设置了，则需要设置“no_proxy”来跳过Qdrant的服务地址。

u r my hero bro
