### ISSUE TITLE
关于qdrant库上传点的时候title选择的问题

### ISSUE THREAD

**Issue by zhaoyiCC** [GanymedeNil/document.ai#14]
我选的是cMedQQ这个数据集，我感觉这个用这个question作为title会不会质量很差呀，因为我现在用的这个数据集（差不多9000多行）建设完成后感觉对于query返回的topK的结果很不好呢

**Comment by zhaoyiCC** [comment]
所以我的感觉是这个title是不是一个病的词会比较好啊

**Comment by GanymedeNil** [comment]
取决于你向量内容主要包含的是病症还是病名，cMedQQ的问题集集中于对具体病的提问，所以肯定是用病名搜索会更好。
