### ISSUE TITLE
关于自训练 Embeddings 问题

### ISSUE THREAD

**Issue by ryzn0518** [GanymedeNil/document.ai#16]
你好，非常感谢作者的贡献，让我更加理解实现思路，我遇到了点问题，想请教您。

如果我自己依据想构建的知识库的数据去训练 Embedding 模型，然后向量化本地数据的时候，同时把训练 Embedding 模型的数据也向量化存储在Qdrant，这样做是不是不合适？

我想基于我们公司已有的想沉淀为知识库的数据进行训练 Embedding，这样期望进行向量化存储和搜索的时候，相似性和准确率稍微可以高点，我该怎么做呢？

**Comment by GanymedeNil** [comment]
> 如果我自己依据想构建的知识库的数据去训练 Embedding 模型，然后向量化本地数据的时候，同时把训练 Embedding 模型的数据也向量化存储在Qdrant，这样做是不是不合适？

训练自己的Embedding模型，其实在这个项目中的意思是训练Embedding模型最后在文本相似性任务上的微调。和实际搜索的向量数据其实不直接相关，你可以这么做。但也需要和OpenAI的Embedding数据进行比对，看哪个最终查询出来的数据满足你的需求。

训练Embedding，你可以看这个项目，已经写的很清楚了
https://github.com/shibing624/text2vec

**Comment by ryzn0518** [comment]
@GanymedeNil 特别感谢你的回复。 [text2vec](https://github.com/shibing624/text2vec) 这个项目我仔细看了，我还是想请教，如果我想训练一个 Embeddings 模型，这个模型主要解决的问题是移动端设备的售后客服领域，您有什么建议吗？

**Comment by SimFG** [comment]
@diaojunxian 最近我做了一个[gptcache](https://github.com/zilliztech/gptcache)项目，第一步是将用户问答进行embedding，目前我用的模型是towhee的uer/albert-base-chinese-cluecorpussmall模型。自己单独训练时为了得到这个模型embedding后有一个更好的向量吗还是，有没有可能选择一个通用模型，在向量数据库的查询结果卡一个距离。不过这部分我也不是很熟悉

**Comment by GanymedeNil** [comment]
> @GanymedeNil 特别感谢你的回复。 [text2vec](https://github.com/shibing624/text2vec) 这个项目我仔细看了，我还是想请教，如果我想训练一个 Embeddings 模型，这个模型主要解决的问题是移动端设备的售后客服领域，您有什么建议吗？

你可以先从通用的bert模型作为Embeddings的开始，如果效果满足预期也不用自己训练了。

**Comment by ryzn0518** [comment]
> 

想再请教你一个关于向量化数据库的问题，如果我想基于一个问答的文档数据库进行向量化存储，想拆分问题和答案分别向量化存储，这里有一个疑问，如何做到分别向量化的数据，如何实现存储到数据库以后能够关联在一起？

**Comment by SimFG** [comment]
可以参考一下gptcache的实现，目前我是通过向量进行hash，通过这个进行关联
@diaojunxian

**Comment by GanymedeNil** [comment]
> > 
> 
> 想再请教你一个关于向量化数据库的问题，如果我想基于一个问答的文档数据库进行向量化存储，想拆分问题和答案分别向量化存储，这里有一个疑问，如何做到分别向量化的数据，如何实现存储到数据库以后能够关联在一起？

你应该要问的是多向量存储和查询吧，可以看这个 #7 。关于数据关联，如果使用qdrant的话可以用payload来关联，其他类似。这个问题就到这里，你可以先学习一下Embeddings理论和向量数据库的实际使用，实际操作后如果还碰到问题欢迎再来提issues。
