### ISSUE TITLE
关于GPT fine-tune

### ISSUE THREAD

**Issue by gusye1234** [GanymedeNil/document.ai#18]
你好, 在readme中看到说对GPT进行finetune效果会变好, 但是在代码中好像没看到fine-tuned相关的操作.
方便问下用于fine-tune的GPT的模型是哪里来的吗? 还是是用的一些开源的foundation model?

谢谢

**Comment by Tavish77** [comment]
想问问时如何finetune的 有代码Demo吗

**Comment by vivian940425** [comment]
> 你好, 在readme中看到说对GPT进行finetune效果会变好, 但是在代码中好像没看到fine-tuned相关的操作. 方便问下用于fine-tune的GPT的模型是哪里来的吗? 还是是用的一些开源的foundation model?
> 
> 谢谢

应该指的就是用 openai 目前的 fine tuning api 把，不过这个目前只能调 3，还不能调 3.5

**Comment by GanymedeNil** [comment]
> 想问问时如何finetune的 有代码Demo吗

就是openAI的fine tuning，openai论坛有很多例子

**Comment by Tavish77** [comment]
> > 想问问时如何finetune的 有代码Demo吗
> 
> 就是openAI的fine tuning，openai论坛有很多例子

不好意思没表述清楚，想问的是embedding模型的fine tune。。。

**Comment by GanymedeNil** [comment]
> > > 想问问时如何finetune的 有代码Demo吗
> > 
> > 
> > 就是openAI的fine tuning，openai论坛有很多例子
> 
> 不好意思没表述清楚，想问的是embedding模型的fine tune。。。

请查看这个项目https://github.com/shibing624/text2vec
