### ISSUE TITLE
怎么解决答案中包含了资料库中没有的答案？

### ISSUE THREAD

**Issue by zaraiah** [GanymedeNil/document.ai#2]
也就是openai瞎胡扯的问题。

**Comment by GanymedeNil** [comment]
就向量数据库而言不会出现没有数据的情况，只是会返回相似度很低的数据。可以加上“如果段落内容不相关就返回未查到"提示词。如下图所示：
![image](https://user-images.githubusercontent.com/9687786/224314723-f9f07bbb-c666-4882-8697-4fd93912a764.png)
