### ISSUE TITLE
请教vectors_config=VectorParams(size=1536, distance=Distance.COSINE)参数问题

### ISSUE THREAD

**Issue by yinjiaoyuan** [GanymedeNil/document.ai#21]
您好！请问vectors_config=VectorParams(size=1536, distance=Distance.COSINE)中1536是怎么计算出来的？我改为其他值例如1000，3000，532都会出错。谢谢。

**Comment by GanymedeNil** [comment]
1536 是 openAI Embeddings模型维度，如果使用其他的Embeddings模型需要改成对应的维度。

**Comment by yinjiaoyuan** [comment]
openAI Embeddings模型维度是在哪里查到的？谢谢。

**Comment by yinjiaoyuan** [comment]
好的，谢谢。

**Comment by GanymedeNil** [comment]
https://platform.openai.com/docs/guides/embeddings/what-are-embeddings
