### ISSUE TITLE
text2vec模型效果怎么样

### ISSUE THREAD

**Issue by chansonZ** [GanymedeNil/document.ai#23]
大佬自训练的版本，看起来不错，效果怎样，有在相关数据集上的评估指标可以分享吗？

比如 text2vec-large-chinese 和 text2vec-base-chinese 的效果对比，便于大家选用

谢谢！

**Comment by GanymedeNil** [comment]
可以查看原作者的比对，我这个在他的基准上有不到2个点的提升

**Comment by PrimarySoulSyntax** [comment]
想问一下，text2vec-large-chinese和text2vec-base-chinese的区别除了维度一个1024，768有区别，还有其他区别吗？text2vec-base-chinese原作者的最大长度是128，你的text2vec-base-chinese和text2vec-large-chinese是基于LERT做的，这个论文中的最大长度是参数512  ，你的text2vec-base-chinese和text2vec-large-chinese最大长度分别是多少呢？

**Comment by GanymedeNil** [comment]
> 想问一下，text2vec-large-chinese和text2vec-base-chinese的区别除了维度一个1024，768有区别，还有其他区别吗？text2vec-base-chinese原作者的最大长度是128，你的text2vec-base-chinese和text2vec-large-chinese是基于LERT做的，这个论文中的最大长度是参数512 ，你的text2vec-base-chinese和text2vec-large-chinese最大长度分别是多少呢？

与LERT一致

**Comment by PrimarySoulSyntax** [comment]
> 

LERT最大长度是512，但是我看你说的其他的地方和text2vec-base-chinese一样。即使LERT最大是512，但是base的训练数据我的理解大多数长度是128左右？所以base的最大长度是128？  即使LERT是512,但是数据是base的数据，在用large的时候长度超过128，即使可以512，是不是效果会有所降低？
期待回复。

**Comment by GanymedeNil** [comment]
理论上不会降低，因为下游任务的训练数据也不是定长的，只要不超过512，效果应该是近似的

**Comment by PrimarySoulSyntax** [comment]
> 理论上不会降低，因为下游任务的训练数据也不是定长的，只要不超过512，效果应该是近似的
好的，感谢！！！！！！
