### ISSUE TITLE
能基于已有的embedding模型，在特定的知识领域上做微调吗？

### ISSUE THREAD

**Issue by yungangwu** [GanymedeNil/document.ai#27]
感谢作者大大的分享，想知道对于计算资源不足的人而言，能不能基于已有的embedding模型在特定的领域知识上做微调，或者类似于lora的方式做增量

**Comment by GanymedeNil** [comment]
embedding模型一般都是需要在特定的领域知识做相关微调，如果是拿bert做embedding，可以具体看bert的微调。

**Comment by yungangwu** [comment]
我现在已经有相关的领域知识了，我想基于你已经训练出来的text2vec-large来做微调，这个可行吗？有相关的方法可以做吗

**Comment by GanymedeNil** [comment]
> 我现在已经有相关的领域知识了，我想基于你已经训练出来的text2vec-large来做微调，这个可行吗？有相关的方法可以做吗

参考https://github.com/shibing624/text2vec 进行数据准备和训练。预训练模型可以和我一样使用https://github.com/ymcui/LERT （最终的文本匹配任务的准确度主要还是依赖预训练模型）。

**Comment by yungangwu** [comment]
感谢，这里的预训练模型是指我们使用的LLM是吧？看样子还是对LLM，针对特定领域知识做lora来的好一些啊

**Comment by GanymedeNil** [comment]
> 感谢，这里的预训练模型是指我们使用的LLM是吧？看样子还是对LLM，针对特定领域知识做lora来的好一些啊

推荐你详细了解一下NLP整个技术路线。你这句话里面有好几处相互矛盾的技术点。如果还有其他与本仓库相关技术问题，可以后续继续提问。

**Comment by Mike4Ellis** [comment]
请问可以用无监督领域文本直接在GanymedeNil/text2vec-large-chinese模型上做微调吗？
