### ISSUE TITLE
SentenceTransformer 调用的问题

### ISSUE THREAD

**Issue by NoobJiahua** [GanymedeNil/document.ai#28]
很感谢作者的分享！
我现在使用LangChain-chatglm项目时碰到了一些加载模型文件的问题，大概确定了是因为模型文件缺少了modules.json，pooling文件夹，还有sentence_xlnet_config.json，这些都从shibing624/text2vec那边复制一份过来会有问题吗，需要有其他特别的设置吗

![image](https://github.com/GanymedeNil/document.ai/assets/75435845/608ce3da-e995-4d92-900d-fa6949e44bdf)

![image](https://github.com/GanymedeNil/document.ai/assets/75435845/f51416e4-3f9e-4dc4-8740-ec22942de67c)

**Comment by GanymedeNil** [comment]
我看了应该没有什么影响

**Comment by NoobJiahua** [comment]
好的好的，那我先close issue了，感谢
