### ISSUE TITLE
对于source data的格式有什么强制要求？

### ISSUE THREAD

**Issue by sologuy** [GanymedeNil/document.ai#3]
参考demo的txt的内容格式，是一定要以#####间隔，还是说这是您摘的原始的MSD数据库的一条？谢谢

**Comment by GanymedeNil** [comment]
是数据的间隔
https://github.com/GanymedeNil/document.ai/blob/af832c37c415bcf5f9bdab1731c516d340368a66/code/data_import/import_data.py#L33
我这里是因为单个数据的文本比较多所以是一个文件是一条数据，然后title和text用#####分隔
导入的代码很简单，你可以改成你需要的格式或导入方式
