### ISSUE TITLE
向量数据库查询到的应该是和问题相似的内容吧

### ISSUE THREAD

**Issue by yuhaowin** [GanymedeNil/document.ai#31]
把用户的 q 转化为向量后，在向量数据库中查询到的 topK 个结果应该是和 q 相似的吧，而不是 q 对应的答案吧？还是说我对向量数据库理解有问题，谢谢。

**Comment by GanymedeNil** [comment]
你理解的没问题，就是这样，如果实际答案和问题在语义上不直接相关就会被忽略。这是已知的问题。

**Comment by yuhaowin** [comment]
好的，如果我想通过用户 q 在向量数据库中找到已知答案的 topK 个相似问题，是不是应该选择 Sentence Similarity 这类模型，这类 Sentence embedding 应该也是和语言相关的对吧，我在 hugging face 上看支持中文、Sentence Similarity 类的 embedding 模型下载最高的是你训练的 GanymedeNil/text2vec-large-chinese。这类模型有好的推荐嘛

**Comment by GanymedeNil** [comment]
> 好的，如果我想通过用户 q 在向量数据库中找到已知答案的 topK 个相似问题，是不是应该选择 Sentence Similarity 这类模型，这类 Sentence embedding 应该也是和语言相关的对吧，我在 hugging face 上看支持中文、Sentence Similarity 类的 embedding 模型下载最高的是你训练的 GanymedeNil/text2vec-large-chinese。这类模型有好的推荐嘛

你可以都试试，看哪个更符合你的业务需求。
