### ISSUE TITLE
您好，请问方便分享text2vec-large/base-chinese的数据集吗

### ISSUE THREAD

**Issue by a656418zz** [GanymedeNil/document.ai#34]
真是相见恨晚，最近研究过来后我也和您有一样的想法，但您5个月前就已经有这个想法了。

因为怕我自己给的数据用于finetune会破坏原来的性能，所以想借助一下您的数据集然后往里面增加我的数据进行一个训练，不知是否方便提供数据集

并不是医疗数据集，而是您开源的两个模型训练所用到的数据集

**Comment by GanymedeNil** [comment]
就是 sts-b 中文翻译数据集，并没有其他的
