### ISSUE TITLE
OpenAI API - Access Terminated😭

### ISSUE THREAD

**Issue by cypggs** [GanymedeNil/document.ai#6]
我加了一行数据导入
cat source_data/004.txt
哮喘#####哮喘发作可表现为突然出现的喘息、咳嗽和呼吸困难。有时哮喘可表现为缓慢发作，症状逐渐加重。无论哪种类型的哮喘发作，哮喘患者都会首先感觉到呼吸困难、咳嗽或胸紧。哮喘发作可以在几分钟后结束，也可持续数小时或数天。胸部或颈部皮肤瘙痒可以是哮喘的早期症状，尤其是儿童。夜间或运动时干咳可以是哮喘唯一的症状。
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/3694954/224546574-fcf1d64d-906f-4b5d-922e-3ab16c65a9f8.png">

马上收到了api禁用，看了使用条例，不能用于健康诊断，大家注意使用，不要api被禁了
![image](https://user-images.githubusercontent.com/3694954/224546488-80ae393c-f912-40ee-8d05-0c4f202f5ce6.png)

ps:不过要大赞这个项目，感觉找到了AIGC的正确使用方式，能自己的数据里训练出一个细分垂直领域的知识库，太牛逼了。

**Comment by GanymedeNil** [comment]
这个我也发现了，在查一些紧急病症的时候会禁用。我会把使用风险贴出来的

**Comment by mobilestack** [comment]
看来需要一个本地部署的小模型了，比如GPT-2，可以考虑做一个配置选项
