### ISSUE TITLE
向量匹配不准确

### ISSUE THREAD

**Issue by martin823823** [GanymedeNil/document.ai#8]
使用GPT接口插入向量及payload到向量数据库，用户输入内容，从向量数据库中返回的数据不是精准的。如下图
![image](https://user-images.githubusercontent.com/12695049/225066569-d78ed722-8646-4f6f-bdb6-f9872b984d6b.png)
![image](https://user-images.githubusercontent.com/12695049/225066723-3cd70017-369d-4fa6-a550-1f0a99007398.png)
这是什么问题引起的呢？

**Comment by martin823823** [comment]
source_data下面数据增加几行就会出现这个问题，请问这是什么原因

**Comment by GanymedeNil** [comment]
> source_data下面数据增加几行就会出现这个问题，请问这是什么原因

单个文件是一条数据，如果你要单文件支持按换行符支持多数据，可以改写导入脚本

**Comment by martin823823** [comment]
使用6个单个文件，每个文件一条数据，用户输入文本，再查询向量数据库，返回的结果也是不准确的。
